import { useState, useEffect } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";

interface Product {
  id: string;
  sku: string;
  name: string;
  description: string;
  stock: number;
  cost: number;
}

const Home: NextPage = () => {
  const [data, setData] = useState<Product[] | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  useEffect(() => {
    if (!isLoading && !data) {
      setIsLoading(true);
      fetch("./api/product")
        .then((res) => res.json())
        .then((data) => setData(data))
        .finally(() => {
          setIsLoading(false);
        });
    }
  }, [data, isLoading]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Next Swagger API Example</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>{isLoading && <>Loading...</>}</div>
        {data && (
          <>
            <h1>Products</h1>
            {data.map((row) => {
              return (
                <ul key={row.id}>
                  <li>name: {row.name}</li>
                  <li>sku: {row.sku}</li>
                  <li>description: {row.description}</li>
                  <li>stock: {row.stock}</li>
                  <li>cost: {row.cost}</li>
                </ul>
              );
            })}
          </>
        )}
      </main>
    </div>
  );
};

export default Home;
